cabal-version:   3.12
name:            bloom
version:         0.1.0.0
license:         NONE
author:          Vi
maintainer:      vi.kitten@proton.me
build-type:      Simple
extra-doc-files: README.md

common warnings
    ghc-options: -Wall

executable bloom
    import:           warnings
    main-is:          Main.hs
    other-modules:    Utils, Frontend, Frontend.Lexer, Frontend.Spanned, Frontend.Parser, Frontend.Main, Inference, Typing, Reporting
    build-depends:    extra, extra, containers, text, free, pipes, transformers, mtl, mmorph, base
    hs-source-dirs:   app
    default-language: Haskell2010
